name: attendance_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  flutter_launcher_icons: ^0.14.3
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  sidebarx: ^0.17.1
  model_viewer_plus: ^1.9.1
  encrypt: ^5.0.3
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  supabase_flutter: ^2.8.4
  image_picker: ^1.1.2
  standard_searchbar: ^2.1.1
  dropdown_textfield: ^1.2.0
  calendar_date_picker2: ^2.0.0
  http: ^1.3.0
  signature: ^5.5.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  url_launcher: ^6.1.12
  flutter_web_auth: ^0.5.0
  flutter_secure_storage: ^4.2.1
  flutter_web_auth_2: ^4.1.0
  google_sign_in: ^6.3.0
  provider: ^6.1.2
  printing: ^5.14.2
  pdf: ^3.11.3
  share_plus: ^10.1.4
  csv: ^6.0.0
  universal_html: ^2.2.4
  fl_chart: ^0.70.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dciLOGO.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/dciLOGO.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/dciLOGO.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/dciLOGO.jpg"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # example:
  fonts:
    - family: SB
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: BL
      fonts:
        - asset: fonts/Poppins-Black.ttf
    - family: B
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: EB
      fonts:
        - asset: fonts/Poppins-ExtraBold.ttf
    - family: EL
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf
    - family: L
      fonts:
        - asset: fonts/Poppins-Light.ttf
    - family: M
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: R
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: T
      fonts:
        - asset: fonts/Poppins-Thin.ttf  
